### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by AndiPersti** [cohomolo-gy/haskell-resources#12]
* The link for "Propositions as Types" loads an overview page. The direct link would be https://www.pure.ed.ac.uk/ws/portalfiles/portal/20001186/propositions_as_types.pdf

* The link for "Generalized Hindley-Milner Systems" is dead. A paper by Heeren et al. from 2002 with the title "Generalizing Hindley-Milner Type Inference Algorithms" is at http://www.cs.uu.nl/research/techreps/repo/CS-2002/2002-031.pdf

**Comment by emilypi** [comment]
Thanks @AndiPersti - a MR would be welcome for updated links
