### ISSUE TITLE
Hey Em. What license is this repo released under?

### ISSUE THREAD

**Issue by ghuntley** [cohomolo-gy/haskell-resources#5]

**Comment by emilypi** [comment]
Hey @ghuntley - No license currently. None of it is my material. All of the links are publicly available and all of the papers released under under their own respective licenses. I am also not the best at licenses, so if you have any idea of what would be most appropriate, I'd be happy to add one 😄

**Comment by emilypi** [comment]
It is now BSD-2. We'll sort out the concerns regarding hosting actual papers on the repository later.
